---
title: "4L. Generics In Java- 1"
---

## Update Autograder

First, please update your autograder by running:

```bash
umm update
```

## Opening Project in IDE

**Project files:** [4L_java_generics_1-TEMPLATE.zip](https://www.dropbox.com/scl/fi/vb00died8l1g96qjaxwc5/4L_java_generics_1-TEMPLATE.zip?rlkey=n7ofqzvu9xtmwi8ikvhojsojy&raw=1)

1. Unzip the files to preferably an `ITSC 2214` folder for this class. You must have created this folder before for previous labs.
2. Open Visual Studio Code.
3. Go to `File > Open Folder`. Choose the folder where you extracted the files.

## Project Overview

Here are the files in your project for the GenerivsPractice package:

```
.
├── src/
│   └── GenericsPractice/
│       └── Pair.java
└── test/
    └── GenericsPractice/
        └── PairTest.java
```

After you read the following, check this:

- This `Pair` class stores two elements of the same generic type.
- Implement the `min` method which returns the smaller of the two elements. These elements must be instances of the `Comparable` interface.

## Rubric

- Project must compile, otherwise no grade.
- Complete JavaDoc for `GenericsPractice.Pair` (5 points)
- All tests passing for `GenericsPractice.PairTest` (20 points)

## Checking Autograder Feedback

1. Open a terminal.
2. Run the command: `umm grade ./script.rhai`

OR

1. Open the command palette with `Ctrl + Shift + P` on Windows and `Cmd + Shift + P` on Mac.
2. Type "run task" and select "Tasks: Run Task". (or "Tasks: Rerun Last Task" in the future).
3. Select the "Grade Assignment" task. Use the other ones as needed but avoid the "Update" task unless told to do so.
4. Select "script.rhai" and press Enter.

You may not have tasks correctly configured for the first few labs.

## Checking Your Grade

{{< include checking_grade.qmd >}}

## Submission

{{< include submission_instructions.qmd  >}}
