name: Preview Quarto Site

on:
  pull_request:
    branches:
      - main

jobs:
  build-preview:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
      - run: quarto install tinytex

      - name: Render Quarto Project
        uses: quarto-dev/quarto-actions/render@v2
        with:
          to: html
          path: .

      - name: Deploy to Netlify
        env:
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
        run: |
          netlify deploy --dir=_site --prod --message="PR Preview: $PR_NUMBER" --alias=$PR_NUMBER

      - name: Create PR Comment
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const pr_number = context.payload.pull_request.number;
            const preview_url = `https://<your-netlify-site>.netlify.app/${pr_number}/`;
            const comment = `Preview the rendered site [here](${preview_url})`;
            github.issues.createComment({
              issue_number: pr_number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: comment,
            });