name: Preview Quarto Site

on:
  pull_request:
    branches:
      - main

jobs:
  build-preview:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
      - run: quarto install tinytex

      - name: Render Quarto Project
        uses: quarto-dev/quarto-actions/render@v2
        with:
          to: html
          path: .

      - name: Deploy to GitHub Pages Preview
        env:
          PR_NUMBER: ${{ github.event.number }}
        run: |
          TARGET_DIR="_site/preview/$PR_NUMBER"
          mkdir -p $TARGET_DIR
          cp -r _site/* $TARGET_DIR/
          cd $TARGET_DIR
          git init
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add .
          git commit -m "PR Preview: $PR_NUMBER"
          git push --force "https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git" master:gh-pages-preview

      - name: Create PR Comment
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const pr_number = context.payload.pull_request.number;
            const comment = `Preview the rendered site [here](https://${{ github.repository_owner }}.github.io/${{ github.repository }}/preview/${pr_number}/)`;
            github.issues.createComment({
              issue_number: pr_number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: comment,
            });
